# Generated by Django 2.2 on 2019-09-18 22:36

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190917_1217'),
        ('freistehende_waende_app', '0001_initial'),
        ('anzeigetafeln_app', '0001_initial'),
        ('freistehendeDaecher_app', '0001_initial'),
        ('flachdaecher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GesamtPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_kopfzeile', stdimage.models.StdImageField(blank=True, upload_to='bilder/')),
                ('pdf_bearbeitet', models.BooleanField(default=False)),
                ('next', models.CharField(blank=True, max_length=80)),
                ('kurz_lang_version', models.CharField(default='text', max_length=80)),
                ('kopfzeilen_art_wahl', models.CharField(default='text', max_length=80)),
                ('anzeigetafeln_app_wahl', models.ManyToManyField(to='anzeigetafeln_app.AnzeigetafelnModel')),
                ('flachdach_app_wahl', models.ManyToManyField(to='flachdaecher_app.FlachdachModel')),
                ('freistehendedaecher_app_wahl', models.ManyToManyField(to='freistehendeDaecher_app.FreistehendeDaecherModel')),
                ('freistehendewaende_app_wahl', models.ManyToManyField(to='freistehende_waende_app.FreistehendeWaende')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allgEingaben')),
            ],
        ),
    ]
