# Generated by Django 2.2 on 2019-09-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gesamt_pdf_app', '0001_initial'),
        ('pultdach_schnee_app', '0001_initial'),
        ('pultdaecher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesamtpdf',
            name='pultdach_app_wahl',
            field=models.ManyToManyField(to='pultdaecher_app.PultdachModel'),
        ),
        migrations.AddField(
            model_name='gesamtpdf',
            name='pultdach_schnee_app_wahl',
            field=models.ManyToManyField(to='pultdach_schnee_app.PultdachSchneeModel'),
        ),
        migrations.AddField(
            model_name='gesamtpdf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
