# Generated by Django 2.2 on 2019-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehldach_schnee_app', '0002_remove_kehldachschneemodel_abrutschen_verhindert'),
        ('gesamt_pdf_app', '0002_auto_20190919_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesamtpdf',
            name='kehldach_schnee_app_wahl',
            field=models.ManyToManyField(to='kehldach_schnee_app.KehldachSchneeModel'),
        ),
    ]
