# Generated by Django 2.2.4 on 2019-09-28 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flachdaecher_app', '0006_auto_20190924_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gesamtgebaeude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_wahl', models.CharField(max_length=100)),
                ('flachdach_app_wahl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flachdaecher_app.FlachdachModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
