# Generated by Django 2.2.4 on 2019-09-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesamtgebaeude_app', '0002_gesamtgebaeude_projekt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesamtgebaeude',
            name='dach_wahl',
            field=models.CharField(default='Dachwahl', max_length=100),
        ),
    ]
