# Generated by Django 2.2.4 on 2019-09-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesamtgebaeude_app', '0003_gesamtgebaeude_dach_wahl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesamtgebaeude',
            name='flachdach_app_wahl',
        ),
    ]
