# Generated by Django 2.2.4 on 2019-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesamtgebaeude_app', '0004_remove_gesamtgebaeude_flachdach_app_wahl'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesamtgebaeude',
            name='edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
