# Generated by Django 2.2.4 on 2019-10-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190917_1217'),
        ('gesamtgebaeude_app', '0005_gesamtgebaeude_edited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesamtgebaeude',
            name='bautteil_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Bauteil'),
        ),
        migrations.AlterField(
            model_name='gesamtgebaeude',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allgEingaben'),
        ),
    ]
