# Generated by Django 2.2.4 on 2019-09-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesamtgebaeude_app', '0005_gesamtgebaeude_edited_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesamtgebaeude',
            name='app_wahl',
        ),
    ]
