# Generated by Django 2.2.4 on 2019-09-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190917_1217'),
        ('gesamtgebaeude_app', '0006_remove_gesamtgebaeude_app_wahl'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesamtgebaeude',
            name='bautteil_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bauteil'),
        ),
    ]
