# Generated by Django 2.2 on 2019-09-15 09:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allgEingaben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_name', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('bundesland', models.CharField(default='Wien', max_length=100)),
                ('ort', models.CharField(default='10.Favoriten', max_length=100)),
                ('gelaendekategorie', models.CharField(default='II', max_length=25)),
                ('winddruck_benutzerdefiniert', models.BooleanField(default=False)),
                ('basiswinddruck', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('basiswinddruck_hidden', models.CharField(blank=True, max_length=100, null=True)),
                ('allgEingaben_eingegeben', models.BooleanField()),
                ('seehoehe_benutzerdefiniert', models.BooleanField(default=False)),
                ('seehoehe', models.DecimalField(decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('seehoehe_hidden', models.CharField(blank=True, max_length=100, null=True)),
                ('windgeschwindigkeit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('abminderungsfaktor', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(max_length=40)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bauteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bautteil_name', models.CharField(max_length=100)),
                ('bemessungsart', models.CharField(blank=True, default='Flachdach', max_length=25, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allgEingaben')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
