# Generated by Django 2.2 on 2019-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bauteil',
            name='bemessungsart',
        ),
        migrations.AddField(
            model_name='bauteil',
            name='bemessungsart_wind_schnee',
            field=models.CharField(blank=True, default='', max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='bauteil',
            name='schnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bauteil',
            name='wind',
            field=models.BooleanField(default=False),
        ),
    ]
