# Generated by Django 2.2 on 2019-09-15 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190915_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgeingaben',
            name='schneelast',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='allgeingaben',
            name='schneelast_benutzerdefiniert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allgeingaben',
            name='schneelastzone',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
