# Generated by Django 2.2 on 2019-09-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_allgeingaben_schneelast_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgeingaben',
            name='schneelastzone',
            field=models.CharField(blank=True, default='2', max_length=10, null=True),
        ),
    ]
