# Generated by Django 2.2 on 2019-09-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190915_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgeingaben',
            name='schneelastzone_hidden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
