# Generated by Django 2.2 on 2019-09-17 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_allgeingaben_schneelastzone_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgeingaben',
            name='basiswinddruck',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='allgeingaben',
            name='windgeschwindigkeit',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
