# Generated by Django 2.2 on 2019-09-18 22:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190917_1217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreistehendeWaende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoehe_ueber_GOK', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('wandhoehe', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('wandlaenge', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('wandverlauf', models.CharField(default='', max_length=30)),
                ('schenkellaenge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('voelligkeitsgrad', models.CharField(default='', max_length=30)),
                ('abschattung', models.CharField(default='', max_length=30)),
                ('abstand_abschattendewand', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('freistehendewaende_eingegeben', models.BooleanField()),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('hoehe_abschattende_wand', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bautteil_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bauteil')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allgEingaben')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
