"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from .email_info import EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_PASSWORD, EMAIL_USE_TLS, EMAIL_HOST_USER, DEFAULT_FROM_EMAIL
from .stripe_info import STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY
import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(bxy$@w-ee0s+=@!klzmriqyr3fhl@^o7x47(-x_^eftb!ell&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Applicatasdasdion definition

INSTALLED_APPS = [
    'account_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',



    'base_app',

    'contact_app',
    'core',
    'freistehende_waende_app',
    'flachdaecher_app',
    'anzeigetafeln_app',
    'freistehendeDaecher_app',
    'pultdaecher_app',
    'waende_app',
    'pultdach_schnee_app',

    'allg_berechnungen_app',

    'gesamt_pdf_app',
    'stdimage',
    'lastaufstellung_app',
    'satteldach_schnee_app',
    'kehldach_schnee_app',







]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

GOOGLE_RECAPTCHA_SECRET_KEY = '6LcU-3IUAAAAAC2I9W1ldv999anL--2LvM3ItKGK'
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'account_app.User'
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


LANGUAGE_CODE = 'de-ch'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
#for gmail

EMAIL_USE_TLS = EMAIL_USE_TLS

EMAIL_HOST = EMAIL_HOST

EMAIL_HOST_USER = EMAIL_HOST_USER

EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD

EMAIL_PORT = EMAIL_PORT

DEFAULT_FROM_EMAIL = DEFAULT_FROM_EMAIL
#stripe
STRIPE_PUBLISHABLE_KEY = STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY = STRIPE_SECRET_KEY
