# Generated by Django 2.2 on 2019-09-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190917_1217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnzeigetafelnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoehe', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('breite', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('abstand_zum_grund', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('anzeigetafeln_eingegeben', models.BooleanField()),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('bautteil_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bauteil')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allgEingaben')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
