# Generated by Django 2.2.4 on 2019-09-28 16:39

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo_kopfzeile',
            field=stdimage.models.StdImageField(blank=True, upload_to='bilder/'),
        ),
    ]
