# Generated by Django 2.2 on 2019-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_nord_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_ost_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_sued_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_west_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
