# Generated by Django 2.2 on 2019-09-23 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0002_auto_20190923_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flachdachmodel',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='breite_x',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='breite_y',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='hoehe',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='hoehe_attika',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_nord_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_ost_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_sued_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_west_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='reibbeiwert_dach',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='reibbeiwert_waende',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
