# Generated by Django 2.2 on 2019-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0003_auto_20190923_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_nord_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
