# Generated by Django 2.2 on 2019-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0004_auto_20190923_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flachdachmodel',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='breite_x',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='breite_y',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='hoehe',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='hoehe_attika',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_nord_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_ost_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_sued_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='oeffnung_west_flaeche',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='reibbeiwert_dach',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flachdachmodel',
            name='reibbeiwert_waende',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
