# Generated by Django 2.2.4 on 2019-09-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0007_auto_20190928_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='flachdachmodel',
            name='gesamtgebaeude',
            field=models.BooleanField(default=False),
        ),
    ]
