# Generated by Django 2.2.4 on 2019-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0007_auto_20190928_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='flachdachmodel',
            name='cpe_wahl',
            field=models.CharField(blank=True, default=1, max_length=80, null=True),
        ),
    ]
