# Generated by Django 2.2.4 on 2019-10-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0008_flachdachmodel_cpe_wahl'),
    ]

    operations = [
        migrations.AddField(
            model_name='flachdachmodel',
            name='cpe_1_einflussflaeche',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
