# Generated by Django 2.2.4 on 2019-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0009_flachdachmodel_cpe_1_einflussflaeche'),
    ]

    operations = [
        migrations.AddField(
            model_name='flachdachmodel',
            name='reibbeiwert_dach_benutzerdef',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='flachdachmodel',
            name='reibbeiwert_waende_benutzerdef',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
