# Generated by Django 2.2.4 on 2019-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flachdaecher_app', '0010_auto_20191020_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='flachdachmodel',
            name='reibbeiwerte_dach_wahl',
            field=models.CharField(default='test', max_length=80),
        ),
        migrations.AddField(
            model_name='flachdachmodel',
            name='reibbeiwerte_waende_wahl',
            field=models.CharField(default='test', max_length=80),
        ),
    ]
