# Generated by Django 2.2 on 2019-09-18 22:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190917_1217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PultdachModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dachneigung', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(75), django.core.validators.MinValueValidator(5)])),
                ('hoehe', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('breite_x', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('breite_y', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('innendruck', models.BooleanField(blank=True, default=True, null=True)),
                ('innendruck_cpi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flaechenparameter_mue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0.33)])),
                ('innendruck_empfohlen', models.BooleanField(blank=True, default=True, null=True)),
                ('verfahren_wahl', models.CharField(max_length=80)),
                ('innendruck_verfahren_wahl', models.CharField(blank=True, default=1, max_length=80, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('pultdach_eingegeben', models.BooleanField()),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('bautteil_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bauteil')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allgEingaben')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
